# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:ios)

platform :ios do

  lane :store_devices do
    register_devices(
      devices: {
        ENV["REGISTER_DEVICE_NAME"] => ENV["REGISTER_DEVICE_ID"]
      }
    )
  end

  lane :signing_cer do
    sync_code_signing(type: ENV["MATCH_OPERATION_TYPE"], app_identifier: ENV["APP_ID"])
  end

  desc "Push a new release build to the App Store"
  lane :release do
    build_app(workspace: "CodoughUIKitSample.xcworkspace", scheme: "CodoughUIKitSample")
    upload_to_app_store(skip_metadata: true, skip_screenshots: true)
  end

end
